#!/usr/bin/python

import datetime, os

from datetime import datetime, date


def main():

    logname = "REPORT"

    os.chdir('./FilesToTest')
    print 'Running the auto-grader'

    # need the "-u" option to make stdout and stderr unbuffered
    # otherwise, the log file is jumbled
    #
    os.system('python -u ../code/VerifyMain.py >& ../'+logname)
    
    
if __name__ == "__main__":
    main()
