#!/usr/bin/python

import datetime, os

from datetime import datetime, date


def main():

    today = date.today()
    time = datetime.now()

    logname = today.strftime("%m-%d-%y-") + time.strftime("%H-%M-%S") + '.log'

    os.chdir('./TarFileGoesHere')
    print 'Running the auto-grader'

    # need the "-u" option to make stdout and stderr unbuffered
    # otherwise, the log file is jumbled
    #
    os.system('python -u ../auto_grade/auto_grade.py >& ../'+logname)    
    
if __name__ == "__main__":
    main()
